#pragma config(Motor,  port2,           leftFront,     tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftBack,      tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port8,           rightFront,    tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightBack,     tmotorVex269_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true) {
		motor[leftFront] = abs(vexRT[Ch3]) < 15 ? 0 : vexRT[Ch3];
		motor[leftBack] = abs(vexRT[Ch3]) < 15 ? 0 : vexRT[Ch3];
		motor[rightFront] = abs(vexRT[Ch2]) < 15 ? 0 : vexRT[Ch2];
		motor[rightBack] = abs(vexRT[Ch2]) < 15 ? 0 : vexRT[Ch2];
	}
}
